language: ruby
services:
  - postgresql
  - redis-server
before_install:
  - gem install bundler
before_script:
  - psql -c 'create database SimpleRate_test;' -U postgres
  - bundle exec rake db:migrate